import Head from 'next/head'
import component from '../styles/Home.module.scss'

const Tasks = () => {
    return <>
        <Head>
            <title>Tasks</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <div className={component.container}>
                <p>Display Task 1 below</p>

                <p>Display Task 2 below</p>
            </div>
        </main>
  </>
}

export default Tasks;
